### ISSUE TITLE
Question: Could you please provide guidance when to use and when not to use memoization?

### ISSUE THREAD

**Issue by AndrewSav** [otac0n/Pegasus#100]
Intuitively it appears that the memoize flag should be added on each and every rule - that's speeding the parsing up with no apparent downside. 

Still we need to opt-in for memoization and we need to do this in every rule.

What are some guidelines that can help deciding whether to memoize a particular rule or not?

**Comment by otac0n** [comment]
I created a profiling tracer that works reasonably well at giving recommendations for specific inputs. Please try using this to investigate the performance of your parser for various inputs.

https://github.com/otac0n/Pegasus/blob/develop/Pegasus.Tests/PerformanceTracer.cs

**Comment by AndrewSav** [comment]
Right @otac0n thank you for getting back to me. I'll see if I can have a look next time around I'm using Pegasus. Which I'm not sure when at all.
