### ISSUE TITLE
New features in V4

### ISSUE THREAD

**Issue by david-pfx** [otac0n/Pegasus#105]
Are there any notes on new features in V4? I found the tracing (thank you), case sensitivity and the start rule, and there is a new function called ParseHelper that I haven't found a use for yet. Anything else I should know about?

**Comment by david-pfx** [comment]
Oops! Found it in the Wiki. Maybe the issue is: please put a link somewhere.

**Comment by otac0n** [comment]
I'll be including release notes in the NuGet packages going forward.
