### ISSUE TITLE
How to recognize strings?

### ISSUE THREAD

**Issue by johnwebner** [otac0n/Pegasus#109]
Hi, I am trying to create a basic Latex parser. I saw some implementations in javascript using PEG.js. Now I am using Pegasus to create the parser in C#.
Unfortunatly I have some issues. I do not fully understand the outputs from the rules.

For example I want to recognize strings containing lower case letters.

**str= c:[a-z]+ { c }**

And I get the following error:
**Cannot implicitly convert type 'System.Collections.Generic.IList<string>' to 'string'**

What exactly is the output of repeated occurrence of expression (in this case c)? Is it a string? an array of chars? Is "**str= c:[a-z]+ { c }**" even valid?

**Comment by johnwebner** [comment]
I tried the following:
**decimal = value:([a-zA-Z]+"") { value }**
and got errors.
Next I have replaced "decimal" by "_decimal":
_decimal = value:([a-zA-Z]+"") { value }
and could recognize strings.

Are some names reserved?
And how to get rid of the quotation mark in
_decimal = value:([a-zA-Z]+"") { value }
?

**Comment by otac0n** [comment]
You can use `string.Concat` if you want to avoid the quotes.

    number = chars:[a-z]i+ { string.Concat(chars) }

This also makes use of case insensitive strings.

Note that it is allowed to use C# keywords as variables, but not as rule names:

    other = decimal:[a-z]i+ { string.Concat(@decimal) }

**Comment by otac0n** [comment]
Discussion related to supporting keywords as names continues in #107
