### ISSUE TITLE
large grammar CS0041 insufficient memory

### ISSUE THREAD

**Issue by piratejon** [otac0n/Pegasus#113]
I have a grammar with a rule of 500 alternating strings most of which include spaces:

    myrule =
        "this is a sentence"
        / "this is a different sentence"
        / "..."
        / "there are about 500 of these sentences"

This worked fine for most inputs but I saw some were wrapping 80-ish characters so I wanted to change the spaces to carriage returns:

    _rn = [ \t\r\n]*
    mynewrule =
        ("this" _rn "is" _rn "a" _rn "sentence")
        / ("this" _rn "is" _rn "a" _rn "different" _rn "sentence")
        / ("...")
        / ("there" _rn "are" _rn "about" _rn "500" _rn "of" _rn "these" _rn "sentences")

When I do this I get this error message on compiling the project:
CS0041 Unexpected error writing debug information -- 'Insufficient memory to continue the execution of the program.' I tried this with both VS2015 (not sure which version) and VS2017 15.7.3 (I don't see any flags to update so I think it is the latest as of today).

I realize this is large, are there any practical or built-in limits to grammar size or complexity?

I am going to try to get around it by breaking the strings up into groups i.e.

    mynewrule = rules0_99 / rules100_200 / rules201_300 / ...
        rules0_99 = first/100/strings
        rules100_200 = next/100/strings
        rules201_300 = next/100/strings
        ...

though I am still wondering about what limits might apply if any.

Update: splitting it into groups of about 100 made it compile and recognize the same things as before. It's a lot slower but I guess that is my own fault. Anyhow I'm still curious about limits if anyone happens to know.

**Comment by otac0n** [comment]
This error, `CS0041 Unexpected error writing debug information -- 'Insufficient memory to continue the execution of the program.` is interesting, can you please provide more details on when and where you saw this message?  Please include a stack trace if possible.

Something that may help with performance, the newest prerelease versions of the NuGet packages contain the workbench and inlcude a performance analysis feature that will give you some help with choosing when to use `-memoize`.

If you cannot use the workbench, you can still see the implementation of the [`WarningsPerformanceTracer`](https://github.com/otac0n/Pegasus/blob/develop/Pegasus.Workbench/Pipeline/TestParser.cs#L89) and may be able to wire-up your own implementation.

Finally, you may want to consider structuring your grammar with common prefixes factored out, like this:

```
mynewrule =
    ("this" _rn "is" _rn "a" _rn ("sentence" / "different" _rn "sentence")
```

This will at least reduce the amount of unnecessary backtracking. You can do this by encoding your data into a [Trie (aka Prefix Tree)](https://en.wikipedia.org/wiki/Trie) before generating your parser code.
