### ISSUE TITLE
Use Pegasus without VS extension?

### ISSUE THREAD

**Issue by dhowe** [otac0n/Pegasus#116]
I'm running on OSX and the plugin doesn't seem to be available. Is it possible to run the tool from the command line ?

**Comment by otac0n** [comment]
The entry point for the app supports taking filenames on the command line:
https://github.com/otac0n/Pegasus/blob/develop/Pegasus/Program.cs

Feasibly, you should be able to run the Pegasus.dll as a console app using .net core.

The build artifacts are here: https://ci.appveyor.com/project/otac0n/pegasus/build/artifacts  
You can find unzip the .nupkg file and find the app under the `build\netcoreapp2.0` folder.

If that doesn't work, you could maybe try running the app from the .csproj directly.

Note that the extension just adds syntax highlighting, all of the functionality of the app comes from the Pegasus.dll which should be able to integrate with your build.

**Comment by Konard** [comment]
Here an example of dynamic compilation of parser using C# Compiler on .NET Core 2.2: https://github.com/Konard/PegasusExample/tree/dynamic-compile
