### ISSUE TITLE
Delayed reaction on key presses with VS extension in .peg file

### ISSUE THREAD

**Issue by gamich** [otac0n/Pegasus#118]
After I have installed the Pegasus extension in my VisualStudio, the reaction on key presses while editing .peg files is delayed. When I enter key presses in a quick sequence, the displaying of the characters is deferred for a few seconds. The .peg file has about 650 lines.

Is this a bug or a feature?

I am working with Pegasus extension version 4.0.14, MS VisualStudio 2017 version 15.9.5, .NET Framework version 4.7.03056.

BTW, thanks for providing Pegasus. I enjoy learning about PEG with it.
Regards

**Comment by otac0n** [comment]
Visual Studio has a feature where the syntax highlighting is throttled to enhance performance.

It is likely that the editor is trying to do it's best with the old highlighting information between key presses until VS decides to invoke the syntax highlighter.

It may be possible to improve this, but I would like to see an example of the behavior.

Closing this for now, if you could provide a .gif or something that shows how to reproduce, I would maybe be able to work toward a resolution.
