### ISSUE TITLE
Not able to cause generation of cs files under .net core 2.2/vs 2017

### ISSUE THREAD

**Issue by xanatos** [otac0n/Pegasus#120]
I'm not able to cause the generation/regeneration of files in a .net core console app (just created) using the latest alpha in nuget. Tried Visual Studio/MSBuild/dotnet build .

**Comment by xanatos** [comment]
Solved... In Visual Studio I can't select the PegGrammar in the properties. Modified manually the csproj .

**Comment by otac0n** [comment]
It should show up if you restart visual studio, BTW.
