### ISSUE TITLE
How do I extract variables from a repetition?

### ISSUE THREAD

**Issue by xanatos** [otac0n/Pegasus#122]
```
Rule <object> = a:A (',' b:B)* EOF { new { a, b } }
A = 'a'
B = 'b'
EOF = !.
```

This is illegal.
Possibilities:

```
Rule <object> = a:A b:(',' B)* EOF { new { a, b } }
A = 'a'
B = 'b'
EOF = !.
```

Ugly, the `','` are returned together with the b (like `,b`)

I can obtain the "right" result with:

Rule <object> = a:A b:SubRule* EOF { new { a, b } }
SubRule = ',' b:B { b }
A = 'a'
B = 'b'
EOF = !.

or compacting everything:

Rule <object> = a:A b:(',' temp:B { temp })* EOF { new { a, b } }
A = 'a'
B = 'b'
EOF = !.

Is this the way to do it, or are there other ways? I haven't found a way to mark some part of the "capture" as "to be ignored"

**Comment by otac0n** [comment]
This can be achieved simply:

    Rule <object> = a:A bList:(',' b:B { b })* { new { a, bList } }

You can also use delimited repetition if the head element and tail elements are of the same type:

    Rule <List<A>> = A<,, ",">
