### ISSUE TITLE
delimit an rule

### ISSUE THREAD

**Issue by furesoft** [otac0n/Pegasus#125]
how can i delimit an rule with for example a comma?
if i do this:
`parameterContent<SyntaxNode> -public
    = _? head:paramDef _? "," tail:parameterContent { SyntaxNode.CreateParameter(head).Concat(tail) }
    / line:paramDef { SyntaxNode.CreateParameter(line) }`

i must write: int x, int y,
but i want: int x, int y

**Comment by otac0n** [comment]
You can use delimited repetition:

```
parameters:paramDef<0, 100, _? "," _?>
```
