### ISSUE TITLE
Expose start cursor in result expression

### ISSUE THREAD

**Issue by segphault** [otac0n/Pegasus#132]
In my result expression, I want to be able to preserve the start and end range of the matched content in the grammar rule, but `state` only appears to provide the position where the matched content ends. I think I need access to the start cursor in addition to the end cursor.

Looking at the generated code, it looks like this would mean adding the extra `startCursor` parameter to the [`wrappedCode`](https://github.com/otac0n/Pegasus/blob/98a2d313af9e5666f37b539f0b5e3c7eb5a11867/Pegasus/Compiler/CodeGenerator/Grammar.weave#L272) invocation in the generated `ReturnHelper` and then changing the signatures accordingly.

**Comment by segphault** [comment]
I figured out that I can use `startCursor0` inside of a result expression. This seems to be working, so maybe that's good enough? Is there any issue with using that variable, or the start/end variables created for the named parts of the grammar rule?

It might be helpful to document which of the variables that are accessible within the result expression scope are safe to use.

**Comment by otac0n** [comment]
If you label your expressions, you will get an extra pair of cursor variables.

https://github.com/otac0n/Pegasus/blob/develop/Pegasus/Parser/PegParser.peg#L98

This is more supported that the indexed expressions.

**Comment by otac0n** [comment]
Alternatively, you can implement ILexical.
