### ISSUE TITLE
Add `-public` flag that will publicly expose a rule for parsing.

### ISSUE THREAD

**Issue by otac0n** [otac0n/Pegasus#42]
Example:

    program = _ expression<0,,_ ';' _> _ EOF
    
    Expression -public = _ e:expression _ { e }
    
    expression = '' [a-z]+

Here, program would still be the start rule and a method called `ParseExpression` would be exposed.

A warning will be emitted if the `-public` flag is added to a rule whose name starts with a lower case letter.

**Comment by davidandl** [comment]
I would use -public to gain access to a rule to use for restarting the parse. The signature need not change. At present I do this via the partial class.

**Comment by otac0n** [comment]
This is now complete in the develop branch.

I also included an `export` flag.

The difference is that the `public` flag's implies a contract like the existing `Parse` method, whereas the `export` flag implies a bare-metal signature.
