### ISSUE TITLE
Support case insensitivity grammar-wide

### ISSUE THREAD

**Issue by mirhagk** [otac0n/Pegasus#53]
It would be nice if you could do something like: `@CaseInsensitive true` to set the whole grammar to have case insensitive literals. This would be really handy for languages like SQL where the entire language is case insensitive. You'd be able to have a cleaner grammar as well as prevent bugs from forgetting to make one of the literals insensitive.

Ideally that'd simply set the default and a new `"foo"s` would be supported to set the literal as sensitive but this probably wouldn't be necessary.

I have an idea of how to implement, but I'm not sure if it's the best way. In `Parser.peg` you could expose the settings through the state variable, and then simply check the settings later on. I can do a pull request for this if you think it's an appropriate solution.

**Comment by otac0n** [comment]
In retrospect, this doesn't change the semantics of any existing grammars.  I'm removing the breaking flag.
