### ISSUE TITLE
Expected ?!!!

### ISSUE THREAD

**Issue by Alobidat** [otac0n/Pegasus#64]
How to report on expected rules when parsing fails, similar to how PEGjs do?

Currently all the feedback we get from the parser is the start rule is not satisfied.

**Comment by otac0n** [comment]
You can add an `#ERROR` expression with a custom error message (even using any in-scope names) to report an expectation in your parser.

See these examples:
* [PegParser.peg:45](/otac0n/Pegasus/blob/v3.1.1/Pegasus/Parser/PegParser.peg#L45)
* [PegParser.peg:119](/otac0n/Pegasus/blob/v3.1.1/Pegasus/Parser/PegParser.peg#L119)
* [PegParser.peg:183](/otac0n/Pegasus/blob/v3.1.1/Pegasus/Parser/PegParser.peg#L183)
* [PegParser.peg:197](/otac0n/Pegasus/blob/v3.1.1/Pegasus/Parser/PegParser.peg#L197)
* [PegParser.peg:211](/otac0n/Pegasus/blob/v3.1.1/Pegasus/Parser/PegParser.peg#L211)
* [PegParser.peg:309](/otac0n/Pegasus/blob/v3.1.1/Pegasus/Parser/PegParser.peg#L309)

There is quite a bit of variety here, which may show you why I chose to use the explicit error route.  For some of these cases, we'd like to put the error marker at the start of the failed string (in the case of code sections, here).  Other times, we may want to put the error at the end of the line (unterminated strings).  Finally, I have a catch-all in my grammar, called EOF, that throws on any character that the parser can't get past.

I found the PEGjs error reporting system to be very helpful in debugging, but not very user friendly.
