### ISSUE TITLE
Latest snapshot generates invalid output?

### ISSUE THREAD

**Issue by AndrewSav** [otac0n/Pegasus#65]
It appears that there has been [a change](https://github.com/otac0n/Pegasus/commit/6be1aecde71e480d499a59ce1fc187bfb702b726) to use `CacheKey` in generated dictionaries. But somehow [this line](https://github.com/otac0n/Pegasus/blob/tracking-4.0/Pegasus/Compiler/CodeGenerator/Rule.weave#L49) was missed during the change which leads to generated code that won't compile because `storage` no longer accepts strings. Am I missing something?

**Comment by otac0n** [comment]
Can you give me a minimum repro case?  I'd like to write some regression tests for this.

**Comment by otac0n** [comment]
Oh, ok.  I see that I have already fixed this back in October: d4d00a22d8b7c959a2fdb2e51372dca56a35002b

I'll ship a release right now, so that you can get going.

**Comment by otac0n** [comment]
I have released v3.1.2

**Comment by AndrewSav** [comment]
Thank you!
