### ISSUE TITLE
Parse tracing

### ISSUE THREAD

**Issue by davidandl** [otac0n/Pegasus#71]
The basic feature is a hook: a user-supplied function to be called on each rule entry and exit passing the rule name and the current state.

A default tracer could keep a stack of the names of each rule leading to the current parse point, updated as it is entered or exited, which could be used in error messages or just to debug a grammar.

If a parse finally fails, it can show all the matches that were made and abandoned along the way.

**Comment by davidandl** [comment]
If a parse finally fails, it can show all the matches that were made and abandoned along the way.

**Comment by deja-cantora** [comment]
I implemented this for an older version of Pegasus here: deja-cantora/Pegasus@cee519cb3f8d13933663708ffd66ef6c11fc26b8

If there's any interest in merging a feature like this, I can try to work on updating it to the head of develop.

**Comment by deja-cantora** [comment]
here's an example of using the feature (treat as an example, probably won't compile without modification):
```
public interface IHasDepth
{
    int Depth();
    int DecrementDepth();
    int IncrementDepth();
}

public interface IMyTracer : IHasDepth {
    void Block();
    void Unblock();
}

public class RuleTrace : IRuleTrace
{
    private IMyTracer obj;
    private bool disposed = false;
    private string rule;
    private int depth;

    // dont continue to trace within these productions
    public static readonly List<string> leaves
        = new List<string>() { "foo", "bar", ... }

    public RuleTrace(IMyTracer obj,
                     string rule)
    {
        this.obj = obj;
        this.depth = this.obj.IncrementDepth();
        this.rule = rule;
        this.log(depth, "[{0}", this.rule);
        Block();
    }

    private bool ShouldBlock() { return leaves.Contains(this.rule); }
    private void Block()
    {
        if(ShouldBlock())
            this.obj.Block();
    }
    private void Unblock()
    {
        if(ShouldBlock())
            this.obj.Unblock();
    }

    private string PrintResult<T>(T value)
    {
        if(value is string)
            return "'"
                   + Print.EscapedString(((dynamic) value))
                   + "'";

        var enumerable = value as System.Collections.IEnumerable;
        if(enumerable != null)
        {
            var result = new StringBuilder("[");
            foreach(var child in enumerable)
                result.Append(PrintResult(child) + ", ");
            result.Append("]");
            return result.ToString();
        }

        return value.ToString();
    }

    private string PrintIParseResult<T>(IParseResult<T> value)
    {
        if(value == null)
            return "<NULL>";

        return PrintResult(value.Value);
    }

    public void Return<T>(IParseResult<T> value)
    {
        this.log(this.depth,
                 " {0}] => {1}",
                 this.rule,
                 PrintIParseResult(value));
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    public virtual void Dispose(bool disposing)
    {
        if(this.disposed)
        {
            throw new InvalidOperationException("this was already disposed!");
        }
        else
        {
            this.disposed = true;
            //ignore disposing variable because we arent freeing managed objects
            Unblock();
            this.obj.DecrementDepth();
        }
    }

    private void log(int depth, string format, params object[] args)
    {
        var prefix = new String(' ', depth);
        Log.Debug(prefix + format, args);
    }
}

class TraceParser : Parser, IMyTracer
{
    private int depth = 0;
    private bool blocking = false;

    public override IRuleTrace RuleTrace(string rule, ref Cursor cursor)
    {
        if(blocking)
            return new NoTrace();

        return new RuleTrace(this, rule);
    }

    public int Depth() { return this.depth; }

    public int DecrementDepth()
    {
        int ret = this.depth;
        this.depth -= 1;
        return ret;
    }

    public int IncrementDepth()
    {
        int ret = this.depth;
        this.depth += 1;
        return ret;
    }

    public void Block() { this.blocking = true; }
    public void Unblock() { this.blocking = false; }
}
```

**Comment by ejsmith** [comment]
I'm definitely interested in this. Not sure how to debug my grammar without it. It seems hard to step through the .peg file.

**Comment by otac0n** [comment]
I would like to allow the author to very easily (1 line of code) make use of System.Diagnostics.Tracing.  This would give access to an enormous range of utilities that work with the built-in tracing.  But, I understand the need for custom tracing, which could perform deep inspection of successful parse results.

Can anyone give me an example of what the output of the tracing would look like?  This will help me think about the right way to implement this.

**Comment by davidandl** [comment]
There are three interesting things to trace in my view.

1.	The entry to and exit from each rule, with the rule name and current position
2.	Each time an action is called, with rule name, position and values of each bound variable
3.	The point at which a rule fails to match, with the rule name and position reached before backtracking.
I would not want all 3 every time – perhaps some bit flags.
It might be useful if they were implemented as virtuals in some class that could be overridden.

**Comment by ejsmith** [comment]
Yeah, I think if we had those things in log messages then it would make it fairly easy to track down issues with our grammars.

**Comment by otac0n** [comment]
This is implemented in the develop branch. Please take a look (esp.  at the end-to-end test)  and let me know if it will work for you.
