### ISSUE TITLE
Error handling to throw a different exception

### ISSUE THREAD

**Issue by davidandl** [otac0n/Pegasus#74]
The purpose is to throw a customised exception in case of various kinds of error. 

A sufficient solution would overriding or replacing the `ExceptionHelper`. It would need a different signature to allow more information to be added.

**Comment by otac0n** [comment]
Could you give an example of how this would be used?

**Comment by davidandl** [comment]
#ERROR{} throws the wrong kind of exception and does not include the information I need. Instead I have used &{} and a custom function to trigger errors. This works fine, but disguises the intention of the code.
This is a minor enhancement to provide a better solution that is currently available.

**Comment by otac0n** [comment]
Considering you have a workaround, nobody else has chimed in on the issue, and that I already plan to alter error handling (#43) to support non-fatal errors, I'm closing this issue.

I do not plan on altering error handling in this way.
