### ISSUE TITLE
Allow additional text to be inserted into subject during parse

### ISSUE THREAD

**Issue by davidandl** [otac0n/Pegasus#76]
Primary purpose: implement #include. Could also be used to implement macros.

The change appears minor: an entry point to simply insert text into the subject and invalidate any relevant cached parse.

A more sophisticated solution might implement Cursor as an interface.

**Comment by otac0n** [comment]
I think this is outside the scope of what Pegasus is trying to achieve.  Even in C and C++ this is done as a step separate from the parser (the preprocessor).

I would strongly recommend against using plain text-insertion in a modern language.

**Comment by davidandl** [comment]
Then with respect, I think you misunderstand. It is a philosophical or language design issue whether to combine the two functions and we may not agree on the choice but consider this.
**In order to implement a pure preprocessor (as for a C or C++ compiler) in Pegasus this feature is essential.**

I agree that there is merit in the idea of separating the preprocessor component, but to implement that it is still necessary to deal with tokens and comments using the same conventions as the host language. I would use Pegasus for that, if I could.

The enhancement is minor: simply enable access to the subject text and allow it to be manipulated during the parse. A couple of access functions would do it.

**Comment by davidandl** [comment]
Actually, turns out to be pretty easy to do. Just save off the cursor, construct a new cursor for the include file, then at the end pop the old one. Done and dusted.

Thought occurs to me: if you had a wiki, I would be happy to add a few how-tos like this one.

**Comment by otac0n** [comment]
I'm using the [Github provided Wiki](https://github.com/otac0n/Pegasus/wiki)

**Comment by johnwebner** [comment]
This would be a very useful feature. I have tried to modify the subject (replace substring) while parsing but it looks like it's still impossible. Is there a workaround?
