### ISSUE TITLE
Allow alternative strategies for parse start, restart, error and finish

### ISSUE THREAD

**Issue by davidandl** [otac0n/Pegasus#77]
Key problems: 
1. Initialisation after the parser starts but before it reads any text
2. Initialisation after processing initial whitespace.
3. Restart after error.
4. Graceful shutdown at end.

Currently the generated code is fixed and things can only be added using partial classes. It would be handy to be able to provide start, restart, exception and finish handlers with different signatures and actions. Perhaps the main parser could subclass from a parent and allow each of these points to be overridden?

**Comment by otac0n** [comment]
Could you give an example grammar that uses these proposed features?

**Comment by davidandl** [comment]
Here is a portion of the Andl grammar.

```
// start rule: Init for error handling, Start to load catalog
MainStart <AstStatement> = &{ PrintLine(state) } &{ SetState(state) } DirectiveOrBlank* &{ Start() } v:MainNext { v }
    / MainRestart;  // suppress warning -- never taken

// Continue after error
MainRestart <AstStatement> =  Skip v:MainNext { v }
```
The restart requires manipulatiing state behind the scenes.
```
    public bool Start() {
      if (_started) return false;
      Logger.WriteLine(4, "Start parse");
      Symbols.ResetScope();
      Symbols.Import(Cat.GlobalVars);
      Symbols.Import(Cat.PersistentVars);
      return true;
    }

    // Called to restart parse after error
    public AstStatement Restart(ref Cursor state) {
      Logger.WriteLine(4, "Restart parse skip={0} line={1} column={2} location={3}", _skip, state.Line, state.Column, state.Location);
      var cursor = state.WithMutability(mutable: false);
      // next line only needed if memoize active
      //this.storage = new Dictionary<CacheKey, object>();

      var restart = _skip;
      _skip = false;
      var result = (restart) ? MainRestart(ref cursor) : MainNext(ref cursor);
      return result.Value;
    }

```
This all works fine, but it's rather clunky.

**Comment by otac0n** [comment]
Pegasus makes every effort to maintain state for you, and already allows you to call and re-call rules in different states.

"Restaring" is not currently a concept that Pegasus understands, and would require a bit of re-architecting to support. In addition, the idea of restarting is counter to some of the core design of Pegasus.

For these reasons, I'm closing this issue.
