### ISSUE TITLE
Update extension for visual studio 2015

### ISSUE THREAD

**Issue by jkoritzinsky** [otac0n/Pegasus#80]
There is no support in the extension for VS2015, so editing in that doesn't have any syntax support from the editor.  If you could update it, that would be great!

**Comment by ejsmith** [comment]
Yes, I want this as well. Any pointers on what needs to be done to support VS 2015?

**Comment by otac0n** [comment]
Can you test the bits here?

https://ci.appveyor.com/project/otac0n/pegasus/build/artifacts

**Comment by ejsmith** [comment]
Seems to be working. I am getting some syntax highlighting in my PEG file now.
