### ISSUE TITLE
Cannot add group to end of expression

### ISSUE THREAD

**Issue by frabert** [otac0n/Pegasus#88]
I believe this is a mistake on my side of some sort, but I really can't understand what's wrong with my grammar:

    1   @namespace LogiC
    2   @classname boh
    3
    4   varDecl
    5     = "int" " "+ name:(("a" / "b" / "c")+) { name }
    6
    7   varDeclStat
    8     = vdecl:varDecl " "* (";" / #error { "error" }) { vdecl }
    9   start = varDeclStat+

The compiler complains at line 8: `Unexpected character '('` referring to the parens opening the group containing the error expression. What am I doing wrong?

**Comment by frabert** [comment]
@otac0n Sorry for the insistence, any ideas on this one?

**Comment by otac0n** [comment]
Hi, thanks for this feedback.

To get this to work, you will need to remove the space between `#error` and `{`.  The error message could be improved.

**Comment by otac0n** [comment]
I'm combining this feedback with another item in #89.
