### ISSUE TITLE
Support @using static 

### ISSUE THREAD

**Issue by madebyjeffrey** [otac0n/Pegasus#98]
I have a number of utility functions that would be very handy to be imported using something like

@using static ....

The functions  would be available in actions.

**Comment by otac0n** [comment]
You should be able to do this:

```
@using { static string }
@using "static DateTime"

a = x:. &{ IsNullOrEmpty(x) };
b = "now" { UtcNow };
```

**Comment by madebyjeffrey** [comment]
I can confirm that this works great. Thank you.
